### ISSUE TITLE
Merge Conflicts in the codebase

### ISSUE THREAD

**Issue by deca7** [amarildolucas/fcm_pusher#2]
I forked this repo with the intention to extend the attributes it can parse. But I've noticed that there's alot of conflicts within the master branch. I compared this to what's published on rubygems.org and it seems the changes there wasn't reflected here. It'd be great if they were synced. I chose to use this gem for a project because of its simplicity. I hope this gets addressed. Thanks!

**Comment by amarildolucas** [comment]
Hi @dc-fc, thanks to notify me about this. I updated the repo here on Github. See if everything it will work without problem now.

**Comment by deca7** [comment]
@amarildolucas Thanks for addressing this. I'll happily close this issue now. :D
